platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: cube-untap

outputs:
- name: compiledApp

run:
  path: ./cube-untap/ci/tasks/test.sh